language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t aryankush25/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aryankush25/docker-react npm run test

after_success:
  - docker build -t aryankush25/multi-client ./client
  - docker build -t aryankush25/multi-nginx ./nginx
  - docker build -t aryankush25/multi-server ./server
  - docker build -t aryankush25/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aryankush25/multi-client
  - docker push aryankush25/multi-nginx
  - docker push aryankush25/multi-server
  - docker push aryankush25/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "complex-docker"
  env: "Complex-docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-404087717260"
  bucket_path: "docker-multi"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
